__all__ = [
    "TRADUCOES",
    "LANGUAGE_ORDER",
    "EXTENSOES_IMAGEM",
    "EXTENSOES_VIDEO",
    "EXTENSOES_SUPORTADAS",
    "PADROES_DATA_NOME",
    "CHECKPOINT_FILENAME",
    "CHECKPOINT_INTERVAL",
]

import re

TRADUCOES = {
    "en": {
        "flag": "EN",
        "lang_name": "English",
        "app_title": "Photo and Video Organizer",
        "select_lang": "Select Language",
        "continue": "Continue",
        "origin": "Source folder:",
        "destination": "Destination folder:",
        "browse": "Browse",
        "dry_run": "Simulate before moving (Dry Run)",
        "copy_instead": "Copy instead of move",
        "organize": "ORGANIZE",
        "log": "Log:",
        "waiting": "Waiting...",
        "done": "Done!",
        "starting": "Starting...",
        "processing": "Processing: {}",
        "no_files": "No supported files found in source folder.",
        "total_found": "Total files found: {}",
        "summary": "SUMMARY",
        "total_processed": "  Total processed       : {}",
        "total_ignored": "  Total ignored          : {}",
        "no_date": "  No date                : {}",
        "sim_mode": "  SIMULATION mode - no files were moved.",
        "init_log": "Starting organization [{}]",
        "sim_label": "SIMULATION",
        "real_label": "REAL EXECUTION",
        "copy_label": "COPY MODE",
        "origin_log": "Source      : {}",
        "dest_log": "Destination : {}",
        "moved": "[MOVED]",
        "copied": "[COPIED]",
        "simulated": "[SIMULATION]",
        "error": "[ERROR]",
        "err_origin": "[ERROR] Please set the source folder.",
        "err_origin_nf": "[ERROR] Source folder not found: {}",
        "err_dest": "[ERROR] Please set the destination folder.",
        "err_move": "[ERROR] Could not move/copy {}: {}",
        "err_permission": "[PERMISSION ERROR] Skipping: {}",
        "select_origin": "Select source folder",
        "select_dest": "Select destination folder",
        "manual_check_folder": "Check_manually",
        "log_saved": "Log saved to: {}",
        "duplicate": "[DUPLICATE]",
        "total_duplicates": "  Duplicates skipped     : {}",
        "checkpoint_resumed": "Resuming from checkpoint: {} files already processed",
        "checkpoint_saved": "Checkpoint saved ({} files)",
        "integrity_ok": "[OK]",
        "integrity_error": "[INTEGRITY ERROR]",
        "total_integrity_errors": "  Integrity errors       : {}",
        "year_dist": "  Year distribution:",
        "total_size": "  Total size             : {}",
        "avg_speed": "  Avg speed              : {} files/sec",
        "total_time": "  Total time             : {}",
        "months": {1: "January", 2: "February", 3: "March", 4: "April", 5: "May", 6: "June", 7: "July", 8: "August", 9: "September", 10: "October", 11: "November", 12: "December"},
    },
    "es": {
        "flag": "ES",
        "lang_name": "Espanol",
        "app_title": "Organizador de Fotos y Videos",
        "select_lang": "Seleccionar Idioma",
        "continue": "Continuar",
        "origin": "Carpeta de origen:",
        "destination": "Carpeta de destino:",
        "browse": "Explorar",
        "dry_run": "Simular antes de mover (Dry Run)",
        "copy_instead": "Copiar en vez de mover",
        "organize": "ORGANIZAR",
        "log": "Registro:",
        "waiting": "Esperando...",
        "done": "Completado!",
        "starting": "Iniciando...",
        "processing": "Procesando: {}",
        "no_files": "No se encontraron archivos compatibles en la carpeta de origen.",
        "total_found": "Total de archivos encontrados: {}",
        "summary": "RESUMEN",
        "total_processed": "  Total procesados       : {}",
        "total_ignored": "  Total ignorados        : {}",
        "no_date": "  Sin fecha              : {}",
        "sim_mode": "  Modo SIMULACION - ningun archivo fue movido.",
        "init_log": "Iniciando organizacion [{}]",
        "sim_label": "SIMULACION",
        "real_label": "EJECUCION REAL",
        "copy_label": "MODO COPIA",
        "origin_log": "Origen      : {}",
        "dest_log": "Destino     : {}",
        "moved": "[MOVIDO]",
        "copied": "[COPIADO]",
        "simulated": "[SIMULACION]",
        "error": "[ERROR]",
        "err_origin": "[ERROR] Indique la carpeta de origen.",
        "err_origin_nf": "[ERROR] Carpeta de origen no encontrada: {}",
        "err_dest": "[ERROR] Indique la carpeta de destino.",
        "err_move": "[ERROR] No se pudo mover/copiar {}: {}",
        "err_permission": "[ERROR DE PERMISO] Omitiendo: {}",
        "select_origin": "Seleccione la carpeta de origen",
        "select_dest": "Seleccione la carpeta de destino",
        "manual_check_folder": "Verificar_manualmente",
        "log_saved": "Log guardado en: {}",
        "duplicate": "[DUPLICADO]",
        "total_duplicates": "  Duplicados omitidos    : {}",
        "checkpoint_resumed": "Reanudando desde checkpoint: {} archivos ya procesados",
        "checkpoint_saved": "Checkpoint guardado ({} archivos)",
        "integrity_ok": "[OK]",
        "integrity_error": "[ERROR DE INTEGRIDAD]",
        "total_integrity_errors": "  Errores de integridad  : {}",
        "year_dist": "  Distribucion por ano:",
        "total_size": "  Tamano total           : {}",
        "avg_speed": "  Velocidad media        : {} archivos/seg",
        "total_time": "  Tiempo total           : {}",
        "months": {1: "Enero", 2: "Febrero", 3: "Marzo", 4: "Abril", 5: "Mayo", 6: "Junio", 7: "Julio", 8: "Agosto", 9: "Septiembre", 10: "Octubre", 11: "Noviembre", 12: "Diciembre"},
    },
    "ru": {
        "flag": "RU",
        "lang_name": "Russkiy",
        "app_title": "Organayzer foto i video",
        "select_lang": "Vybor yazyka",
        "continue": "Prodolzhit",
        "origin": "Iskhodnaya papka:",
        "destination": "Papka naznacheniya:",
        "browse": "Obzor",
        "dry_run": "Simulyatsiya pered peremeshcheniyem (Dry Run)",
        "copy_instead": "Kopirovat vmesto peremeshcheniya",
        "organize": "ORGANIZOVAT",
        "log": "Zhurnal:",
        "waiting": "Ozhidaniye...",
        "done": "Gotovo!",
        "starting": "Zapusk...",
        "processing": "Obrabotka: {}",
        "no_files": "Podderzhivayemye fayly ne naydeny v iskhodnoy papke.",
        "total_found": "Vsego naydeno faylov: {}",
        "summary": "ITOG",
        "total_processed": "  Obrabotano             : {}",
        "total_ignored": "  Propushcheno           : {}",
        "no_date": "  Bez daty               : {}",
        "sim_mode": "  Rezhim SIMULYATSII - fayly ne peremeshchalis.",
        "init_log": "Zapusk organizatsii [{}]",
        "sim_label": "SIMULYATSIYA",
        "real_label": "REALNYY ZAPUSK",
        "copy_label": "REZHIM KOPIROVANIYA",
        "origin_log": "Istochnik   : {}",
        "dest_log": "Naznacheniye: {}",
        "moved": "[PEREMESHCHENO]",
        "copied": "[SKOPIROVANO]",
        "simulated": "[SIMULYATSIYA]",
        "error": "[OSHIBKA]",
        "err_origin": "[OSHIBKA] Ukazhite iskhodnuyu papku.",
        "err_origin_nf": "[OSHIBKA] Iskhodnaya papka ne naydena: {}",
        "err_dest": "[OSHIBKA] Ukazhite papku naznacheniya.",
        "err_move": "[OSHIBKA] Ne udalos peremestit/skopirovat {}: {}",
        "err_permission": "[OSHIBKA DOSTUPA] Propusk: {}",
        "select_origin": "Vyberte iskhodnuyu papku",
        "select_dest": "Vyberte papku naznacheniya",
        "manual_check_folder": "Proverit_vruchnuyu",
        "log_saved": "Zhurnal sokhranen v: {}",
        "duplicate": "[DUBLIKAT]",
        "total_duplicates": "  Dublikaty propushcheny : {}",
        "checkpoint_resumed": "Vozobnovleniye s tochki kontrolya: {} faylov uzhe obrabotano",
        "checkpoint_saved": "Tochka kontrolya sokhranena ({} faylov)",
        "integrity_ok": "[OK]",
        "integrity_error": "[OSHIBKA TSELOSTNOSTI]",
        "total_integrity_errors": "  Oshibki tselostnosti   : {}",
        "year_dist": "  Raspredeleniye po godam:",
        "total_size": "  Obshchiy razmer        : {}",
        "avg_speed": "  Sred. skorost          : {} faylov/sek",
        "total_time": "  Obshcheye vremya       : {}",
        "months": {1: "Yanvar", 2: "Fevral", 3: "Mart", 4: "Aprel", 5: "May", 6: "Iyun", 7: "Iyul", 8: "Avgust", 9: "Sentyabr", 10: "Oktyabr", 11: "Noyabr", 12: "Dekabr"},
    },
    "zh": {
        "flag": "ZH",
        "lang_name": "Zhongwen",
        "app_title": "Zhaopian he shipin zhengliji",
        "select_lang": "Xuanze yuyan",
        "continue": "Jixu",
        "origin": "Yuan wenjianjia:",
        "destination": "Mubiao wenjianjia:",
        "browse": "Liulan",
        "dry_run": "Yidong qian moni yunxing (Dry Run)",
        "copy_instead": "Fuzhi er bu shi yidong",
        "organize": "ZHENGLI",
        "log": "Rizhi:",
        "waiting": "Dengdai zhong...",
        "done": "Wancheng!",
        "starting": "Qidong zhong...",
        "processing": "Zheng zai chuli: {}",
        "no_files": "Zai yuan wenjianjia zhong wei zhaodao zhichi de wenjian.",
        "total_found": "Gong zhaodao wenjian: {}",
        "summary": "ZHAIYAO",
        "total_processed": "  Yi chuli               : {}",
        "total_ignored": "  Yi hulue               : {}",
        "no_date": "  Wu riqi                : {}",
        "sim_mode": "  Moni moshi - meiyou wenjian bei yidong.",
        "init_log": "Kaishi zhengli [{}]",
        "sim_label": "MONI",
        "real_label": "SHIJI ZHIXING",
        "copy_label": "FUZHI MOSHI",
        "origin_log": "Laiyuan     : {}",
        "dest_log": "Mubiao      : {}",
        "moved": "[YI YIDONG]",
        "copied": "[YI FUZHI]",
        "simulated": "[MONI]",
        "error": "[CUOWU]",
        "err_origin": "[CUOWU] Qing shezhi yuan wenjianjia.",
        "err_origin_nf": "[CUOWU] Wei zhaodao yuan wenjianjia: {}",
        "err_dest": "[CUOWU] Qing shezhi mubiao wenjianjia.",
        "err_move": "[CUOWU] Wufa yidong/fuzhi {}: {}",
        "err_permission": "[QUANXIAN CUOWU] Tiaoguo: {}",
        "select_origin": "Xuanze yuan wenjianjia",
        "select_dest": "Xuanze mubiao wenjianjia",
        "manual_check_folder": "Shou_dong_jian_cha",
        "log_saved": "Rizhi yi baocun zhi: {}",
        "duplicate": "[CHONGFU]",
        "total_duplicates": "  Chongfu tiaoguo        : {}",
        "checkpoint_resumed": "Cong jiancha dian jixu: {} ge wenjian yi chuli",
        "checkpoint_saved": "Jiancha dian yi baocun ({} ge wenjian)",
        "integrity_ok": "[OK]",
        "integrity_error": "[WANZHENGXING CUOWU]",
        "total_integrity_errors": "  Wanzhengxing cuowu     : {}",
        "year_dist": "  Nian fen bu:",
        "total_size": "  Zong da xiao           : {}",
        "avg_speed": "  Ping jun su du         : {} ge/miao",
        "total_time": "  Zong shi jian          : {}",
        "months": {1: "Yiyue", 2: "Eryue", 3: "Sanyue", 4: "Siyue", 5: "Wuyue", 6: "Liuyue", 7: "Qiyue", 8: "Bayue", 9: "Jiuyue", 10: "Shiyue", 11: "Shiyiyue", 12: "Shi_eryue"},
    },
}

LANGUAGE_ORDER = ["en", "es", "ru", "zh"]

EXTENSOES_IMAGEM = {
    ".jpg", ".jpeg", ".jpe", ".jif", ".jfif", ".jfi",
    ".png", ".apng",
    ".gif",
    ".bmp", ".dib",
    ".tiff", ".tif",
    ".webp",
    ".heic", ".heif",
    ".avif",
    ".jxl",
    ".svg", ".svgz",
    ".ico", ".cur",
    ".psd", ".psb",
    ".ai", ".eps",
    ".cr2", ".cr3", ".crw",
    ".nef", ".nrw",
    ".arw", ".srf", ".sr2",
    ".raf",
    ".orf",
    ".rw2",
    ".pef", ".ptx",
    ".rwl",
    ".srw",
    ".x3f",
    ".kdc", ".dcr",
    ".mrw",
    ".dng", ".raw", ".3fr", ".erf", ".mef", ".mos",
    ".exr", ".hdr", ".rgbe",
    ".tga", ".icb", ".vda", ".vst",
    ".pcx",
    ".xbm", ".xpm",
    ".wmf", ".emf",
    ".xcf",
    ".ppm", ".pgm", ".pbm", ".pnm", ".pfm",
    ".sgi", ".rgb", ".rgba", ".bw",
    ".j2k", ".jp2", ".jpf", ".jpx", ".jpm", ".mj2",
}

EXTENSOES_VIDEO = {
    ".mp4", ".m4v", ".m4p",
    ".mov", ".qt",
    ".avi",
    ".mkv", ".mk3d",
    ".wmv", ".asf",
    ".flv", ".f4v", ".f4p",
    ".3gp", ".3g2", ".3gpp", ".3gpp2",
    ".mpg", ".mpeg", ".mpe", ".mpv", ".m1v", ".m2v",
    ".ts", ".mts", ".m2ts", ".tp", ".trp",
    ".vob",
    ".webm",
    ".ogv", ".ogg",
    ".rm", ".rmvb",
    ".divx",
    ".mxf",
    ".dv", ".dif",
    ".swf",
    ".amv", ".nsv", ".yuv", ".gifv",
}

EXTENSOES_SUPORTADAS = EXTENSOES_IMAGEM | EXTENSOES_VIDEO

PADROES_DATA_NOME = [
    re.compile(r'(?<!\d)(20\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])(?!\d)'),
    re.compile(r'(20\d{2})[-_](0[1-9]|1[0-2])[-_](0[1-9]|[12]\d|3[01])'),
]

CHECKPOINT_FILENAME = "organize_checkpoint.json"
CHECKPOINT_INTERVAL = 50
